CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Series" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Series" PRIMARY KEY ("Id")
);

CREATE TABLE "Webinar" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "StartDateTime" timestamp without time zone NOT NULL,
    "Duration" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "SeriesId" integer NOT NULL,
    "EndDateTime" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Webinar" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Webinar_Series_SeriesId" FOREIGN KEY ("SeriesId") REFERENCES "Series" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Webinar_SeriesId" ON "Webinar" ("SeriesId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200710224607_InitialCreate', '3.1.5');

CREATE UNIQUE INDEX "IX_Series_Name" ON "Series" ("Name");

CREATE UNIQUE INDEX "IX_Webinar_Name" ON "Webinar" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200711113652_UniqueFields', '3.1.5');

ALTER TABLE "Series" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200712085131_AddSoftDeleteInSeries', '3.1.5');